name: willmod
description: Collection of class for rapid apps development
version: 0.0.1
homepage: https://github.com/AngrySperm/willmod

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # Base
  cupertino_icons: 1.0.2
  nb_utils: 4.4.8
  intl: 0.17.0
  dio: 4.0.4
  http: 0.13.0
  json_annotation: 4.6.0
  flutter_dotenv: 5.0.2
  shared_preferences: 2.0.7
  local_auth: 2.1.0

  # # Production
  # flutter_native_splash: 1.2.4
  # flutter_launcher_icons: 0.9.0
  # flutter_app_name: 0.1.0

  # STATE MANAGEMENT
  get: 4.6.1

  # IMAGES
  cached_network_image: 3.1.0

  # UI
  flutter_easyloading: 3.0.3
  google_fonts: 2.0.0
  loadmore: 2.0.1
  calendar_view: 0.0.5
  wave: 0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - images/

  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito-Regular.ttf
        - asset: fonts/Nunito-Italic.ttf
          style: italic
        - asset: fonts/Nunito-Medium.ttf
          weight: 500
        - asset: fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: fonts/Nunito-Bold.ttf
          weight: 700
        - asset: fonts/Nunito-ExtraBold.ttf
          weight: 800

  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
